FROM node:18-alpine AS base

# Объявляем build-args
ARG NEXT_PUBLIC_SITE_NAME_ARG
ARG NEXT_PUBLIC_ADDRESS_ARG
ARG NEXT_PUBLIC_CITY_LOCATION_ARG
ARG NEXT_PUBLIC_DOMEN_ARG
ARG NEXT_PUBLIC_MAIN_TEL_ARG
ARG NEXT_PUBLIC_FIRST_MANAGER_TEL_ARG
ARG NEXT_PUBLIC_FIRST_MANAGER_NAME_ARG
ARG NEXT_PUBLIC_FIRST_MANAGER_EMAIL_ARG
ARG NEXT_PUBLIC_SECOND_MANAGER_TEL_ARG
ARG NEXT_PUBLIC_SECOND_MANAGER_NAME_ARG
ARG NEXT_PUBLIC_SECOND_MANAGER_EMAIL_ARG
ARG REVALIDATE_SECRET_ARG

# Этап 1: Установка зависимостей
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# Этап 2: Сборка приложения
FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Преобразуем ARG в ENV
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME_ARG}
ENV NEXT_PUBLIC_ADDRESS=${NEXT_PUBLIC_ADDRESS_ARG}
ENV NEXT_PUBLIC_CITY_LOCATION=${NEXT_PUBLIC_CITY_LOCATION_ARG}
ENV NEXT_PUBLIC_DOMEN=${NEXT_PUBLIC_DOMEN_ARG}
ENV NEXT_PUBLIC_MAIN_TEL=${NEXT_PUBLIC_MAIN_TEL_ARG}
ENV NEXT_PUBLIC_FIRST_MANAGER_TEL=${NEXT_PUBLIC_FIRST_MANAGER_TEL_ARG}
ENV NEXT_PUBLIC_FIRST_MANAGER_NAME=${NEXT_PUBLIC_FIRST_MANAGER_NAME_ARG}
ENV NEXT_PUBLIC_FIRST_MANAGER_EMAIL=${NEXT_PUBLIC_FIRST_MANAGER_EMAIL_ARG}
ENV NEXT_PUBLIC_SECOND_MANAGER_TEL=${NEXT_PUBLIC_SECOND_MANAGER_TEL_ARG}
ENV NEXT_PUBLIC_SECOND_MANAGER_NAME=${NEXT_PUBLIC_SECOND_MANAGER_NAME_ARG}
ENV NEXT_PUBLIC_SECOND_MANAGER_EMAIL=${NEXT_PUBLIC_SECOND_MANAGER_EMAIL_ARG}
ENV REVALIDATE_SECRET=${REVALIDATE_SECRET_ARG} 

ENV NODE_ENV=production
RUN npm run build

# Этап 3: Запуск
FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]