version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_CITY_LOCATION_ARG=${NEXT_PUBLIC_CITY_LOCATION}
        - NEXT_PUBLIC_DOMEN_ARG=${NEXT_PUBLIC_DOMEN}
        - NEXT_PUBLIC_MAIN_TEL_ARG=${NEXT_PUBLIC_MAIN_TEL}
        - NEXT_PUBLIC_SITE_NAME_ARG=${NEXT_PUBLIC_SITE_NAME}
        - NEXT_PUBLIC_ADDRESS_ARG=${NEXT_PUBLIC_ADDRESS}
        - NEXT_PUBLIC_FIRST_MANAGER_TEL_ARG=${NEXT_PUBLIC_FIRST_MANAGER_TEL}
        - NEXT_PUBLIC_FIRST_MANAGER_NAME_ARG=${NEXT_PUBLIC_FIRST_MANAGER_NAME}
        - NEXT_PUBLIC_FIRST_MANAGER_EMAIL_ARG=${NEXT_PUBLIC_FIRST_MANAGER_EMAIL}
        - NEXT_PUBLIC_SECOND_MANAGER_TEL_ARG=${NEXT_PUBLIC_SECOND_MANAGER_TEL}
        - NEXT_PUBLIC_SECOND_MANAGER_NAME_ARG=${NEXT_PUBLIC_SECOND_MANAGER_NAME}
        - NEXT_PUBLIC_SECOND_MANAGER_EMAIL_ARG=${NEXT_PUBLIC_SECOND_MANAGER_EMAIL}
        - BITRIX_KEY_ARG=${BITRIX_KEY}
        - REVALIDATE_SECRET_ARG=${REVALIDATE_SECRET}
        - PORT_ARG=${APP_PORT:-3000}
    image: kitkars-nextjs-app:latest
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - content_data:/app/app/content
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: unless-stopped

  scripts-runner:
    build:
      context: .
      dockerfile: Dockerfile.scripts
      args:
        - DB_URL_ARG=${DB_URL}
        - WC_KEY_ARG=${WC_KEY}
        - WC_SECRET_ARG=${WC_SECRET}
        - REVALIDATE_SECRET_ARG=${REVALIDATE_SECRET}
    image: kitkars-scripts:latest
    volumes:
      - content_data:/app/app/content
    environment:
      - NODE_ENV=production
    env_file:
      - .env.secrets
    restart: unless-stopped

volumes:
  content_data:
