import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const montserratSans = Montserrat({
    variable: "--font-montserrat-sans",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en, ru'>
            <body className={`${montserratSans.className}`}>{children}</body>
        </html>
    );
}
